- Id: 10115010
  CardInfoPositionType: 3
  CardInfoDisplayStartTimeSeconds: 19000
  UrCardEffectBackgroundId: 10160
- Id: 10215010
  CardInfoPositionType: 3
  CardInfoDisplayStartTimeSeconds: 17500
  UrCardEffectBackgroundId: 10160
- Id: 10215020
  CardInfoPositionType: 3
  CardInfoDisplayStartTimeSeconds: 17000
  UrCardEffectBackgroundId: 10690
- Id: 10215030
  CardInfoPositionType: 3
  CardInfoDisplayStartTimeSeconds: 19000
  UrCardEffectBackgroundId: 10360
- Id: 10215040
  CardInfoPositionType: 3
  CardInfoDisplayStartTimeSeconds: 16500
  UrCardEffectBackgroundId: 10760
- Id: 10215050
  CardInfoPositionType: 3
  CardInfoDisplayStartTimeSeconds: 19000
  UrCardEffectBackgroundId: 10980
- Id: 10215060
  CardInfoPositionType: 3
  CardInfoDisplayStartTimeSeconds: 26000
  UrCardEffectBackgroundId: 10920
- Id: 10215070
  CardInfoPositionType: 3
  CardInfoDisplayStartTimeSeconds: 21500
  UrCardEffectBackgroundId: 10920
- Id: 10215080
  CardInfoPositionType: 3
  CardInfoDisplayStartTimeSeconds: 26000
  UrCardEffectBackgroundId: 10750
- Id: 10215090
  CardInfoPositionType: 3
  CardInfoDisplayStartTimeSeconds: 26000
  UrCardEffectBackgroundId: 10740
- Id: 10215100
  CardInfoPositionType: 3
  CardInfoDisplayStartTimeSeconds: 24500
  UrCardEffectBackgroundId: 10850
- Id: 10215110
  CardInfoPositionType: 3
  CardInfoDisplayStartTimeSeconds: 21000
  UrCardEffectBackgroundId: 10100
- Id: 10215120
  CardInfoPositionType: 3
  CardInfoDisplayStartTimeSeconds: 29500
  UrCardEffectBackgroundId: 10141
- Id: 10215130
  CardInfoPositionType: 3
  CardInfoDisplayStartTimeSeconds: 32000
  UrCardEffectBackgroundId: 11501
- Id: 10215140
  CardInfoPositionType: 3
  CardInfoDisplayStartTimeSeconds: 29000
  UrCardEffectBackgroundId: 10070
- Id: 10215150
  CardInfoPositionType: 3
  CardInfoDisplayStartTimeSeconds: 20000
  UrCardEffectBackgroundId: 15000
- Id: 10215161
  CardInfoPositionType: 3
  CardInfoDisplayStartTimeSeconds: 25500
  UrCardEffectBackgroundId: 10540
- Id: 10215170
  CardInfoPositionType: 3
  CardInfoDisplayStartTimeSeconds: 26000
  UrCardEffectBackgroundId: 10070
- Id: 10215180
  CardInfoPositionType: 3
  CardInfoDisplayStartTimeSeconds: 23500
  UrCardEffectBackgroundId: 10160
- Id: 10225010
  CardInfoPositionType: 3
  CardInfoDisplayStartTimeSeconds: 17800
  UrCardEffectBackgroundId: 10100
- Id: 10225020
  CardInfoPositionType: 3
  CardInfoDisplayStartTimeSeconds: 16500
  UrCardEffectBackgroundId: 10760
- Id: 10225030
  CardInfoPositionType: 3
  CardInfoDisplayStartTimeSeconds: 21000
  UrCardEffectBackgroundId: 10160
- Id: 10225040
  CardInfoPositionType: 3
  CardInfoDisplayStartTimeSeconds: 20000
  UrCardEffectBackgroundId: 10920
- Id: 10225050
  CardInfoPositionType: 3
  CardInfoDisplayStartTimeSeconds: 17000
  UrCardEffectBackgroundId: 10990
- Id: 10225060
  CardInfoPositionType: 3
  CardInfoDisplayStartTimeSeconds: 18000
  UrCardEffectBackgroundId: 10740
- Id: 10225070
  CardInfoPositionType: 3
  CardInfoDisplayStartTimeSeconds: 20000
  UrCardEffectBackgroundId: 10030
- Id: 10225080
  CardInfoPositionType: 3
  CardInfoDisplayStartTimeSeconds: 16000
  UrCardEffectBackgroundId: 10980
- Id: 10225090
  CardInfoPositionType: 3
  CardInfoDisplayStartTimeSeconds: 18500
  UrCardEffectBackgroundId: 10100
- Id: 10225100
  CardInfoPositionType: 3
  CardInfoDisplayStartTimeSeconds: 22000
  UrCardEffectBackgroundId: 10340
- Id: 10225110
  CardInfoPositionType: 3
  CardInfoDisplayStartTimeSeconds: 20000
  UrCardEffectBackgroundId: 10970
- Id: 10225120
  CardInfoPositionType: 3
  CardInfoDisplayStartTimeSeconds: 17000
  UrCardEffectBackgroundId: 10141
- Id: 10225130
  CardInfoPositionType: 3
  CardInfoDisplayStartTimeSeconds: 15000
  UrCardEffectBackgroundId: 10160
- Id: 10225140
  CardInfoPositionType: 3
  CardInfoDisplayStartTimeSeconds: 24000
  UrCardEffectBackgroundId: 10920
- Id: 10225150
  CardInfoPositionType: 3
  CardInfoDisplayStartTimeSeconds: 16000
  UrCardEffectBackgroundId: 15000
- Id: 10225160
  CardInfoPositionType: 3
  CardInfoDisplayStartTimeSeconds: 29500
  UrCardEffectBackgroundId: 0
- Id: 10225170
  CardInfoPositionType: 3
  CardInfoDisplayStartTimeSeconds: 24000
  UrCardEffectBackgroundId: 11601
- Id: 10225180
  CardInfoPositionType: 3
  CardInfoDisplayStartTimeSeconds: 16500
  UrCardEffectBackgroundId: 10160
- Id: 10235010
  CardInfoPositionType: 3
  CardInfoDisplayStartTimeSeconds: 17500
  UrCardEffectBackgroundId: 10340
- Id: 10235020
  CardInfoPositionType: 3
  CardInfoDisplayStartTimeSeconds: 17000
  UrCardEffectBackgroundId: 11250
- Id: 10235030
  CardInfoPositionType: 3
  CardInfoDisplayStartTimeSeconds: 25000
  UrCardEffectBackgroundId: 10160
- Id: 10235040
  CardInfoPositionType: 3
  CardInfoDisplayStartTimeSeconds: 27000
  UrCardEffectBackgroundId: 10141
- Id: 10235050
  CardInfoPositionType: 3
  CardInfoDisplayStartTimeSeconds: 33000
  UrCardEffectBackgroundId: 10100
- Id: 10235060
  CardInfoPositionType: 3
  CardInfoDisplayStartTimeSeconds: 27500
  UrCardEffectBackgroundId: 11150
- Id: 10235070
  CardInfoPositionType: 3
  CardInfoDisplayStartTimeSeconds: 38000
  UrCardEffectBackgroundId: 11511
- Id: 10235080
  CardInfoPositionType: 3
  CardInfoDisplayStartTimeSeconds: 33000
  UrCardEffectBackgroundId: 10970
- Id: 10235090
  CardInfoPositionType: 3
  CardInfoDisplayStartTimeSeconds: 25500
  UrCardEffectBackgroundId: 10340
- Id: 10235100
  CardInfoPositionType: 3
  CardInfoDisplayStartTimeSeconds: 22500
  UrCardEffectBackgroundId: 15000
- Id: 10235110
  CardInfoPositionType: 3
  CardInfoDisplayStartTimeSeconds: 27000
  UrCardEffectBackgroundId: 11280
- Id: 10235120
  CardInfoPositionType: 3
  CardInfoDisplayStartTimeSeconds: 18000
  UrCardEffectBackgroundId: 11470
- Id: 10235130
  CardInfoPositionType: 3
  CardInfoDisplayStartTimeSeconds: 32500
  UrCardEffectBackgroundId: 10990
- Id: 10235140
  CardInfoPositionType: 3
  CardInfoDisplayStartTimeSeconds: 20500
  UrCardEffectBackgroundId: 10160
- Id: 10315010
  CardInfoPositionType: 3
  CardInfoDisplayStartTimeSeconds: 17500
  UrCardEffectBackgroundId: 10020
- Id: 10315020
  CardInfoPositionType: 3
  CardInfoDisplayStartTimeSeconds: 17000
  UrCardEffectBackgroundId: 10020
- Id: 10315030
  CardInfoPositionType: 3
  CardInfoDisplayStartTimeSeconds: 17500
  UrCardEffectBackgroundId: 10850
- Id: 10315040
  CardInfoPositionType: 3
  CardInfoDisplayStartTimeSeconds: 15500
  UrCardEffectBackgroundId: 10850
- Id: 10315050
  CardInfoPositionType: 3
  CardInfoDisplayStartTimeSeconds: 15500
  UrCardEffectBackgroundId: 10760
- Id: 10315060
  CardInfoPositionType: 3
  CardInfoDisplayStartTimeSeconds: 19000
  UrCardEffectBackgroundId: 10740
- Id: 10315070
  CardInfoPositionType: 3
  CardInfoDisplayStartTimeSeconds: 22000
  UrCardEffectBackgroundId: 10510
- Id: 10315080
  CardInfoPositionType: 3
  CardInfoDisplayStartTimeSeconds: 19000
  UrCardEffectBackgroundId: 10680
- Id: 10315090
  CardInfoPositionType: 3
  CardInfoDisplayStartTimeSeconds: 19500
  UrCardEffectBackgroundId: 11250
- Id: 10315100
  CardInfoPositionType: 3
  CardInfoDisplayStartTimeSeconds: 26500
  UrCardEffectBackgroundId: 11250
- Id: 10315110
  CardInfoPositionType: 3
  CardInfoDisplayStartTimeSeconds: 23000
  UrCardEffectBackgroundId: 11300
- Id: 10315120
  CardInfoPositionType: 3
  CardInfoDisplayStartTimeSeconds: 25000
  UrCardEffectBackgroundId: 11430
- Id: 10315130
  CardInfoPositionType: 3
  CardInfoDisplayStartTimeSeconds: 28500
  UrCardEffectBackgroundId: 10070
- Id: 10315140
  CardInfoPositionType: 3
  CardInfoDisplayStartTimeSeconds: 23000
  UrCardEffectBackgroundId: 10160
- Id: 10315150
  CardInfoPositionType: 3
  CardInfoDisplayStartTimeSeconds: 20500
  UrCardEffectBackgroundId: 11601
- Id: 10315160
  CardInfoPositionType: 3
  CardInfoDisplayStartTimeSeconds: 15000
  UrCardEffectBackgroundId: 11680
- Id: 10315170
  CardInfoPositionType: 3
  CardInfoDisplayStartTimeSeconds: 26000
  UrCardEffectBackgroundId: 15000
- Id: 10315181
  CardInfoPositionType: 3
  CardInfoDisplayStartTimeSeconds: 26000
  UrCardEffectBackgroundId: 10540
- Id: 10315190
  CardInfoPositionType: 3
  CardInfoDisplayStartTimeSeconds: 26500
  UrCardEffectBackgroundId: 10900
- Id: 10315200
  CardInfoPositionType: 3
  CardInfoDisplayStartTimeSeconds: 25500
  UrCardEffectBackgroundId: 11970
- Id: 10325010
  CardInfoPositionType: 3
  CardInfoDisplayStartTimeSeconds: 17500
  UrCardEffectBackgroundId: 10750
- Id: 10325020
  CardInfoPositionType: 3
  CardInfoDisplayStartTimeSeconds: 17000
  UrCardEffectBackgroundId: 10760
- Id: 10325030
  CardInfoPositionType: 3
  CardInfoDisplayStartTimeSeconds: 17000
  UrCardEffectBackgroundId: 10910
- Id: 10325040
  CardInfoPositionType: 3
  CardInfoDisplayStartTimeSeconds: 19500
  UrCardEffectBackgroundId: 10030
- Id: 10325050
  CardInfoPositionType: 3
  CardInfoDisplayStartTimeSeconds: 22000
  UrCardEffectBackgroundId: 10920
- Id: 10325060
  CardInfoPositionType: 3
  CardInfoDisplayStartTimeSeconds: 16000
  UrCardEffectBackgroundId: 10990
- Id: 10325070
  CardInfoPositionType: 3
  CardInfoDisplayStartTimeSeconds: 17000
  UrCardEffectBackgroundId: 10090
- Id: 10325080
  CardInfoPositionType: 3
  CardInfoDisplayStartTimeSeconds: 19000
  UrCardEffectBackgroundId: 10250
- Id: 10325090
  CardInfoPositionType: 3
  CardInfoDisplayStartTimeSeconds: 18000
  UrCardEffectBackgroundId: 10580
- Id: 10325100
  CardInfoPositionType: 3
  CardInfoDisplayStartTimeSeconds: 20000
  UrCardEffectBackgroundId: 11250
- Id: 10325110
  CardInfoPositionType: 3
  CardInfoDisplayStartTimeSeconds: 17500
  UrCardEffectBackgroundId: 11320
- Id: 10325120
  CardInfoPositionType: 3
  CardInfoDisplayStartTimeSeconds: 14500
  UrCardEffectBackgroundId: 11030
- Id: 10325130
  CardInfoPositionType: 3
  CardInfoDisplayStartTimeSeconds: 18000
  UrCardEffectBackgroundId: 10051
- Id: 10325140
  CardInfoPositionType: 3
  CardInfoDisplayStartTimeSeconds: 15000
  UrCardEffectBackgroundId: 11601
- Id: 10325150
  CardInfoPositionType: 3
  CardInfoDisplayStartTimeSeconds: 20000
  UrCardEffectBackgroundId: 15040
- Id: 10325160
  CardInfoPositionType: 3
  CardInfoDisplayStartTimeSeconds: 17500
  UrCardEffectBackgroundId: 10760
- Id: 10325170
  CardInfoPositionType: 3
  CardInfoDisplayStartTimeSeconds: 29000
  UrCardEffectBackgroundId: 15000
- Id: 10325180
  CardInfoPositionType: 3
  CardInfoDisplayStartTimeSeconds: 25000
  UrCardEffectBackgroundId: 10160
- Id: 10335010
  CardInfoPositionType: 3
  CardInfoDisplayStartTimeSeconds: 17500
  UrCardEffectBackgroundId: 10740
- Id: 10335020
  CardInfoPositionType: 3
  CardInfoDisplayStartTimeSeconds: 15000
  UrCardEffectBackgroundId: 11250
- Id: 10335030
  CardInfoPositionType: 3
  CardInfoDisplayStartTimeSeconds: 16000
  UrCardEffectBackgroundId: 11180
- Id: 10335040
  CardInfoPositionType: 3
  CardInfoDisplayStartTimeSeconds: 17000
  UrCardEffectBackgroundId: 10970
- Id: 10335050
  CardInfoPositionType: 3
  CardInfoDisplayStartTimeSeconds: 19000
  UrCardEffectBackgroundId: 10311
- Id: 10335060
  CardInfoPositionType: 3
  CardInfoDisplayStartTimeSeconds: 17000
  UrCardEffectBackgroundId: 11040
- Id: 10335070
  CardInfoPositionType: 3
  CardInfoDisplayStartTimeSeconds: 12000
  UrCardEffectBackgroundId: 10030
- Id: 10335080
  CardInfoPositionType: 3
  CardInfoDisplayStartTimeSeconds: 14000
  UrCardEffectBackgroundId: 10100
- Id: 10335090
  CardInfoPositionType: 3
  CardInfoDisplayStartTimeSeconds: 23000
  UrCardEffectBackgroundId: 11640
- Id: 10335100
  CardInfoPositionType: 3
  CardInfoDisplayStartTimeSeconds: 22000
  UrCardEffectBackgroundId: 15030
- Id: 10335110
  CardInfoPositionType: 3
  CardInfoDisplayStartTimeSeconds: 24000
  UrCardEffectBackgroundId: 10160
- Id: 10335120
  CardInfoPositionType: 3
  CardInfoDisplayStartTimeSeconds: 24000
  UrCardEffectBackgroundId: 15000
- Id: 10335130
  CardInfoPositionType: 3
  CardInfoDisplayStartTimeSeconds: 23000
  UrCardEffectBackgroundId: 11720
- Id: 10335140
  CardInfoPositionType: 3
  CardInfoDisplayStartTimeSeconds: 21000
  UrCardEffectBackgroundId: 10560
- Id: 10415010
  CardInfoPositionType: 3
  CardInfoDisplayStartTimeSeconds: 30500
  UrCardEffectBackgroundId: 10020
- Id: 10415020
  CardInfoPositionType: 3
  CardInfoDisplayStartTimeSeconds: 27500
  UrCardEffectBackgroundId: 10160
- Id: 10415030
  CardInfoPositionType: 3
  CardInfoDisplayStartTimeSeconds: 30000
  UrCardEffectBackgroundId: 10740
- Id: 10425010
  CardInfoPositionType: 3
  CardInfoDisplayStartTimeSeconds: 16500
  UrCardEffectBackgroundId: 11040
- Id: 10425020
  CardInfoPositionType: 3
  CardInfoDisplayStartTimeSeconds: 18500
  UrCardEffectBackgroundId: 10160
- Id: 10435010
  CardInfoPositionType: 3
  CardInfoDisplayStartTimeSeconds: 19500
  UrCardEffectBackgroundId: 10030
- Id: 10435020
  CardInfoPositionType: 3
  CardInfoDisplayStartTimeSeconds: 13500
  UrCardEffectBackgroundId: 10160
- Id: 10435030
  CardInfoPositionType: 3
  CardInfoDisplayStartTimeSeconds: 23000
  UrCardEffectBackgroundId: 10160
